[platformio]
; NOTE: fix for neovim `jump-to-definition` using `clangd`
src_dir = Src

[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = stlink
monitor_port = /dev/cu.usbmodem33*
build_flags =
  -IInc
